apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: videostream
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: jvieira22/videostream:latest
spec:
  project: default

  source:
    repoURL: https://github.com/jonvieirac/sd_phpsite.git
    path: dev
    targetRevision: HEAD
  destination: 
    server: https://kubernetes.default.svc
    namespace: sdapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Replace=true

    automated:
      selfHeal: true
      prune: true
